# Dockerfile
FROM mysql:8.0

# Variables de entorno por defecto (puedes sobreescribir en Railway)
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Exponer puerto
EXPOSE 3306

# Comando por defecto
CMD ["mysqld"]
